In [1]:
'''
!python -m spacy download en
!python -m spacy download en_vectors_web_lg
!pip install nltk
'''
import nltk
'''
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
'''


"\nnltk.download('punkt')\nnltk.download('wordnet')\nnltk.download('stopwords')\n"

In [2]:
#!pip install spacy

In [3]:
#!python -m spacy download en
#!python -m spacy download en_vectors_web_lg

In [4]:
import pandas as pd
import numpy as np
data = pd.read_csv('medium_data.csv')
data.head(10)

id                                                url  \
0   1  https://towardsdatascience.com/a-beginners-gui...   
1   2  https://towardsdatascience.com/hands-on-graph-...   
2   3  https://towardsdatascience.com/how-to-use-ggpl...   
3   4  https://towardsdatascience.com/databricks-how-...   
4   5  https://towardsdatascience.com/a-step-by-step-...   
5   6  https://towardsdatascience.com/an-easy-introdu...   
6   7  https://towardsdatascience.com/hypothesis-test...   
7   8  https://towardsdatascience.com/introduction-to...   
8   9  https://towardsdatascience.com/which-2020-cand...   
9  10  https://towardsdatascience.com/what-if-ai-mode...   

                                               title  \
0  A Beginner’s Guide to Word Embedding with Gens...   
1  Hands-on Graph Neural Networks with PyTorch & ...   
2                       How to Use ggplot2 in Python   
3  Databricks: How to Save Files in CSV on Your L...   
4  A Step-by-Step Implementation of Gradient Desc...   
5    An Easy Introduction to SQL for Data Scientists   
6                      Hypothesis testing visualized   
7  Introduction to Latent Matrix Factorization Re...   
8       Which 2020 Candidate is the Best at Twitter?   
9          What if AI model understanding were easy?   

                                            subtitle   image  claps responses  \
0                                                NaN   1.png    850         8   
1                                                NaN   2.png   1100        11   
2                   A Grammar of Graphics for Python   3.png    767         1   
3            When I work on Python projects dealing…  4.jpeg    354         0   
4                    One example of building neural…  5.jpeg    211         3   
5                                                NaN  6.jpeg    563         1   
6               Literally seeing how stat tests work   7.gif    276         1   
7                                                NaN   8.png    126         2   
8  A Data Analysis of the 2020 Democratic Candida...   9.png    188         3   
9  See  analytics-for-AI in action in this What-I...  10.jpg    493         2   

   reading_time           publication        date  
0             8  Towards Data Science  2019-05-30  
1             9  Towards Data Science  2019-05-30  
2             5  Towards Data Science  2019-05-30  
3             4  Towards Data Science  2019-05-30  
4             4  Towards Data Science  2019-05-30  
5             8  Towards Data Science  2019-05-30  
6            12  Towards Data Science  2019-05-30  
7             5  Towards Data Science  2019-05-30  
8             8  Towards Data Science  2019-05-30  
9             8  Towards Data Science  2019-05-30

In [5]:
df=data[['id','title','subtitle']]
df.loc[df['subtitle']=='A Grammar of Graphics for Python']

id                         title                          subtitle
2   3  How to Use ggplot2 in Python  A Grammar of Graphics for Python

In [6]:
df

id                                              title  \
0        1  A Beginner’s Guide to Word Embedding with Gens...   
1        2  Hands-on Graph Neural Networks with PyTorch & ...   
2        3                       How to Use ggplot2 in Python   
3        4  Databricks: How to Save Files in CSV on Your L...   
4        5  A Step-by-Step Implementation of Gradient Desc...   
...    ...                                                ...   
6503  6504  “We” vs “I” — How Should You Talk About Yourse...   
6504  6505                   How Donald Trump Markets Himself   
6505  6506      Content and Marketing Beyond Mass Consumption   
6506  6507  5 Questions All Copywriters Should Ask Clients...   
6507  6508             How To Write a Good Business Blog Post   

                                               subtitle  
0                                                   NaN  
1                                                   NaN  
2                      A Grammar of Graphics for Python  
3               When I work on Python projects dealing…  
4                       One example of building neural…  
...                                                 ...  
6503              Basic copywriting choices with a big…  
6504  Lessons from who might be the most popular bra...  
6505  How to acquire customers without wasting money...  
6506                           Save time and effort by…  
6507                    An A-to-Z guide for non-writers  

[6508 rows x 3 columns]

In [7]:
sentences = ['Author writes on Medium', 'Readers reads and writes comment on Medium', 'Viewers appreciates author']
df_ohe = pd.DataFrame({"text":sentences, "output":[1,1,0]})

In [8]:
df_ohe

text  output
0                     Author writes on Medium       1
1  Readers reads and writes comment on Medium       1
2                  Viewers appreciates author       0

### ONE HOT ENCODING
#### One hot encoding means converting words of your document in a V-dimension vector and by combining all this we get a single document so at the end we have a two-dimensional array

#### Disadvantages

1) Sparsity – You can see that only a single sentence creates a vector of n*m size where n is the length of sentence m is a number of unique words in a document and 80 percent of values in a vector is zero.

2) No fixed Size – Each document is of a different length which creates vectors of different sizes and cannot feed to the model.

3) Does not capture semantics – The core idea is we have to convert text into numbers by keeping in mind that the actual meaning of a sentence should be observed in numbers that are not seen in one-hot encoding.

In [9]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(
    categories='auto',  # Categories per feature
    drop=None, # Whether to drop one of the features
    sparse=True, # Will return sparse matrix if set True
    handle_unknown='error' # Whether to raise an error
) 
transformed = ohe.fit_transform(df_ohe[['text']])
print(transformed.toarray())
print(ohe.categories_)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[array(['Author writes on Medium',
       'Readers reads and writes comment on Medium',
       'Viewers appreciates author'], dtype=object)]


In [10]:
transformed_med=ohe.fit_transform(df[['title']])

In [11]:
print(transformed_med.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### BAG OF WORDS
#### It is one of the most used text vectorization techniques. It is mostly used in text classification tasks. Bag of words is a little bit similar to one-hot encoding where we enter each word as a binary value and in a Bag of words we keep a single row and entry the count of words in a document. So we create a vocabulary and for a single document, we enter one entry of which words occur how many times in a document.

Advantages

1) Simple and intuitive – Only a few lines of code are required to implement the technique.

2) Fix size vector – The problem which we saw in one-hot encoding where we are unable to feed data the data to machine learning model because each sentence forms a different size vector but here It ignores the new words and takes only words which are vocabulary so creates a vector of fix size.

Disadvantages

1) Out of vocabulary situation – It keeps count of vocabulary words so if new words come in a sentence it simply ignores it and tracks the count of the words that are in vocabulary. But what if the words it ignores are important in predicting the outcome so this is a disadvantage, only benefit is it does not throw an error.

2) Sparsity – when we have a large vocabulary, and the document contains a few repeated terms then it creates a sparse array.

3) Not considering ordering is an issue – It is difficult to estimate the semantics of the document.

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow = cv.fit_transform(df['title'])

In [13]:
str(dict(list(cv.vocabulary_.items())[0: 5]))

"{'beginner': 749, 'guide': 3117, 'to': 7053, 'word': 7666, 'embedding': 2312}"

In [14]:
print(bow[0].toarray())

[[0 0 0 ... 0 0 0]]


### using nltk and spacy 
## data processsing function

In [25]:
import nltk
nltk.download('omw-1.4')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import unicodedata
import re
STOPWORDS = stopwords.words('english')
lemmatizer = WordNetLemmatizer()

def process_text(text):
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    #text = text.translate(str.maketrans('', '', string.punctuation))
    text = text.lower()
    text = " ".join([word for word in str(text).split() if word not in STOPWORDS])
    text = " ".join([lemmatizer.lemmatize(word) for word in text.split()])
    return text

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...


### Defining and Processing the Corpus

In [26]:
data_sentences = df['title'].to_list()
corpus = data_sentences[:50]
print(corpus)
process_corpus = np.vectorize(process_text)
processed_corpus = process_corpus(corpus)
print(processed_corpus)

['A Beginner’s Guide to Word Embedding with Gensim Word2Vec\xa0Model', 'Hands-on Graph Neural Networks with PyTorch & PyTorch Geometric', 'How to Use ggplot2 in\xa0Python', 'Databricks: How to Save Files in CSV on Your Local\xa0Computer', 'A Step-by-Step Implementation of Gradient Descent and Backpropagation', 'An Easy Introduction to SQL for Data Scientists', 'Hypothesis testing visualized', 'Introduction to Latent Matrix Factorization Recommender Systems', 'Which 2020 Candidate is the Best at\xa0Twitter?', 'What if AI model understanding were\xa0easy?', '<em class="markup--em markup--h3-em">What I Learned from (Two-time) Kaggle Grandmaster Abhishek\xa0Thakur</em>', 'Making a DotA2 Bot Using\xa0ML', 'Building A ‘Serverless’ Chrome Extension', 'How to Teach\xa0Code', 'Reinventing Personalization For Customer Experience', 'How to Automate Hyperparameter Optimization', 'Ideas: Design Methodologies for Data\xa0Sprints', 'RoboSomm Chapter 3: Wine Embeddings and a Wine Recommender', 'Data S

In [30]:
count_vect = CountVectorizer(min_df = 0., max_df = 1.)
matrix = count_vect.fit_transform(processed_corpus)
matrix.toarray()
print(matrix.toarray())

[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
